spring.application.name=19-User-form

spring.datasource.username=root
spring.datasource.password=somya
spring.datasource.url=jdbc:mysql://localhost:3306/somya

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

server.port=8082
